_core:
  default_config_hash: 4GIX5Esnc_umpXUBj4IIocRX7Mt5fPhm4AgXfE3E56E
module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  announcements_feed: 0
  automated_cron: 0
  better_exposed_filters: 0
  big_pipe: 0
  block: 0
  block_content: 0
  blockgroup: 0
  blog: 0
  breakpoint: 0
  cache_control_override: 0
  ckeditor5: 0
  comment: 0
  config: 0
  contact: 0
  content_entity_clone: 0
  content_sync: 0
  contextual: 0
  country: 0
  custom_likes: 0
  datetime: 0
  dblog: 0
  dynamic_entity_reference: 0
  dynamic_page_cache: 0
  editor: 0
  entity: 0
  entity_reference_revisions: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  history: 0
  image: 0
  js_cookie: 0
  link: 0
  link_attributes: 0
  menu_link_content: 0
  menu_ui: 0
  merchant_dashboard: 0
  mobile_number: 0
  mobile_otp: 0
  mysql: 0
  node: 0
  node_to_pdf: 0
  options: 0
  otp_verification: 0
  page_cache: 0
  path: 0
  path_alias: 0
  quick_node_clone: 0
  range: 0
  redirect_after_login: 0
  role_based_registration: 0
  search: 0
  serialization: 0
  shortcut: 0
  sms: 0
  sms_sendtophone: 0
  sms_user: 0
  smtp: 0
  svg_image: 0
  system: 0
  taxonomy: 0
  telephone: 0
  tester_dashboard: 0
  text: 0
  token: 0
  toolbar: 0
  twig_tweak: 0
  typed_data: 0
  update: 0
  user: 0
  views_ui: 0
  virtual_select: 0
  pathauto: 1
  views: 10
  paragraphs: 11
  views_taxonomy_radios_filter: 11
  standard: 1000
theme:
  olivero: 0
  claro: 0
  review_likes: 0
  gin: 0
profile: standard
